### ISSUE TITLE
Strange generated output

### ISSUE THREAD

**Issue by yug125lk** [sangmain/Face-Frontalization#1]
hi, thank you for sharing these codes, I have an issue please, concerned the generated output, when I tried " autoencoder_unet_vggface"
I got images with red and blacks colors. I tried to change the scale of pixels to [0,1] or [0, 255], from these two lines  
but it doesn't work. Thank you in advance.

`generated_image = 0.5 * self.AE.predict(side_image) + 0.5    `
`side_image = (255 * ((side_image)+1)/2).astype(np.uint8)`

![output](https://github.com/sangmain/Face-Frontalization/assets/127154096/ab0294ce-4589-41aa-8ede-784a24044f4c)

**Comment by sangmain** [comment]
Hi, thanks for the attention to the project.

As you've mentioned that "generated_image" are saved strangely,
Are "side_image" saved normally?

If so, then try scaling "generated_image" to [0,255] as is done for "side_image"
`generated_image = 0.5 * self.AE.predict(side_image) + 0.5 `
`generated_image = (255 * ((generated_image)+1)/2).astype(np.uint8)`

**Comment by yug125lk** [comment]
Thank you so much for your response, the side_image are saved normally, I tried to scale the generated_image same as the side one , but the results also look strange (just grey color). 
I have updated the first comment putting the image.
![second](https://github.com/sangmain/Face-Frontalization/assets/127154096/d500ee2e-2be1-48d1-8b25-910abd49d4f1)

**Comment by sangmain** [comment]
It looks like the output of the model is already in good scale.
Try printing the scale and type of the generated image.
The model simply seems to be underfitted.

**Comment by yug125lk** [comment]
Hi, The problem was in my dataloader. Now it works. Thank you.

**Comment by yug125lk** [comment]
Hi, The problem was in my dataloader. Now it works. Thank you.
